<a href="https://colab.research.google.com/github/NatashaMyruta/Numerical-methods/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_4_1_%D0%9C%D0%B8%D1%80%D1%83%D1%82%D0%B0_ipynb%22%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Мирута Наталія Романівна ФІТ 2-15

In [1]:
import numpy as np
np.__version__

'2.0.2'

1. Створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [2]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[4, 1, 2],
       [4, 5, 5],
       [1, 5, 2]])

2. Обчислити визначник матриці

In [3]:
det = np.linalg.det(matrix)
det

np.float64(-33.0)

3. Знайти добуток всіх елементів матриці

In [4]:
product = np.prod(matrix)
product

np.int64(8000)

In [6]:
prod_1= np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3= np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(8000)

4. Знайти суму всіх елементів матриці

In [7]:
sum = np.sum(matrix)
sum

np.int64(29)

5. Обчислити найбільший, найменший елементи

In [8]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


6. Знайти середнє значення елементів матриці

In [9]:
mean = np.mean (matrix)
print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 3.2222222222222223


7. Знайти матрицю, що складена з квадратних коренів.

In [10]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[2.         1.         1.41421356]
 [2.         2.23606798 2.23606798]
 [1.         2.23606798 1.41421356]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [12]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор стовпчик

Сума елементів кожного рядка:
[[ 7]
 [14]
 [ 8]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [15]:
vector = np.random.randint(0, 10, size=25)
print("Початковий вектор:")
print (vector)
# Сортуємо числа за спаданням
sorted_vector = np.sort(vector) [::-1]
print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[7 5 5 1 4 0 7 4 3 1 8 7 1 1 7 3 6 2 3 3 7 6 8 5 4]
Вектор після сортування за спаданням:
[8 8 7 7 7 7 7 6 6 5 5 5 4 4 4 3 3 3 3 2 1 1 1 1 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [17]:
from scipy import stats
# Знаходимо моду
mode = stats.mode(vector)
# Знаходимо медіану
median = np.median(vector)
# Знаходимо середнє
mean = np.mean (vector)
# Знаходимо максимальне значення
max_value = np.max(vector)
# Знаходимо мінімальне значення
min_value = np.min(vector)
print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(7), count=np.int64(5))
Медіана: 4.0
Середнє: 4.32
Максимальне значення: 8
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [18]:
# Створюємо дві матриці 4х4 із випадкових цілих чисел від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[10  1  7 10]
 [ 1  8  4  8]
 [ 2  4  5  9]
 [ 1  8  9  7]]

Матриця 2:
[[ 4  1 10  4]
 [ 4  3  3  9]
 [ 2  9  2  4]
 [ 2  1  2  5]]


In [30]:
# обчислюємо суму матриць
matrix_sum = matrix1 + matrix2
# обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2
# обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2
# обчислюємо поелементну частку матриць
# Для запобігання ділення на нуль, використовуємо пр.divide з параметром where matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)


Сума матриць:
[[14  2 17 14]
 [ 5 11  7 17]
 [ 4 13  7 13]
 [ 3  9 11 12]]

Різниця матриць:
[[ 6  0 -3  6]
 [-3  5  1 -1]
 [ 0 -5  3  5]
 [-1  7  7  2]]

Поелементний добуток матриць:
[[40  1 70 40]
 [ 4 24 12 72]
 [ 4 36 10 36]
 [ 2  8 18 35]]


12. Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що містить числа 0.0-2.0

In [22]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [23]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [24]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [25]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

13. Задати вектор-рядок (числа 1-5). Обчислити вектор в кубі.

In [27]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [28]:
np.power (x1, 3)

array([  0,   1,   8,  27,  64, 125])

14. Піднести до ступеня

In [29]:
x2= np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])